export class AlgebraicEffect {
    constructor(...params){
        this.params = params;
    }
}

export function effectHandler({tryCode, handleCode}){
    let nextValue = {value: undefined, done: false};
    let tryCodeGenerator;
    if (tryCode?.constructor.name === "GeneratorFunction"){
        tryCodeGenerator = tryCode();
    }else{
        tryCodeGenerator = tryCode;
    }
    while (!nextValue.done){
        nextValue = tryCodeGenerator.next(
            (nextValue.value?.constructor.name === "AlgebraicEffect") ? 
                handleCode(...nextValue.value.params)
            :
                undefined
        );
    }
    if (typeof nextValue.value !== "undefined"){
        return nextValue.value;
    }
}

export function* chainEffectHandler({tryCode, handleCode}){
    let nextValue = {value: undefined, done: false};
    let tryCodeGenerator;
    // initalize try code function
    if (tryCode?.constructor.name === "GeneratorFunction"){
        tryCodeGenerator = tryCode();
    }else{
        tryCodeGenerator = tryCode;
    }

    while (!nextValue.done){
        // nextArgs are the args to the next function of the tryCode generator
        let nextArgs = undefined;

        // if the value found by the last execution of the tryCode function was an algebraic effect
        if (nextValue.value?.constructor.name === "AlgebraicEffect"){
            // if handleCode is a generator
            if (handleCode?.constructor.name === "GeneratorFunction"){
                // initalize generation objects
                let handleGenerator = handleCode(...nextValue.value.params);
                let nextHandleValue = {value: undefined, done: false};

                while(!nextHandleValue.done){
                    // update call the next function on handleGenerator (if it generated an Algebraic Effect
                    // with the last yield statement, call the handler with that effect as the input to the
                    // next function)
                    nextHandleValue = handleGenerator.next(
                        (nextHandleValue.value?.constructor.name === "AlgebraicEffect") ? 
                            yield nextHandleValue.value
                        :
                            undefined
                    );
                }

                // if the handler didn't return/yield anything by the time it finished
                if (typeof nextHandleValue.value === "undefined"){
                    // bubble the algebraic effect up by yielding the algebraic effect generated by the
                    // tryCode generator
                    nextArgs = yield nextValue.value;
                }else{
                    // if the handler did turn up a value, return it to the tryCode by passing it into the
                    // next function call of the try gode genrator
                    nextArgs = nextHandleValue.value;
                }
            }else{
                // the handleCode is not a generator, just evaluate it
                nextArgs = handleCode(...nextValue.value.params)
            }
        }

        // step through the trycode generator given the next args to the trycode generator object function
        nextValue = tryCodeGenerator.next(nextArgs);
    }
    if (typeof nextValue.value !== "undefined"){
        // when the trycode generator finishes, if it returned a value, return that value from this
        // chainEffectHandler as well
        return nextValue.value;
    }
}

/*
example algebraic effect:

function* getName(user) {
    let name = user.name;
    if (name === null) {
        name = yield new AlgebraicEffect('ask_name',false);
    }
    return name;
}
 
function* makeFriends(user1, user2) {
    user2.friendNames.push(yield* getName(user1));
    user1.friendNames.push(yield* getName(user2));
}

let arya = { name: null, friendNames: [] };
let gendry = { name: 'Gendry', friendNames: [] };
effectHandler({
    tryCode: chainEffectHandler({
        tryCode: function* () {
            yield* makeFriends(arya, gendry);
        },
        handleCode: function*(effect, log) {
            console.log(effect);
            if (log){
                console.log("a");
            }
            if (effect === 'ask_name') {
                return yield new AlgebraicEffect('get_name');
            }
        }
    }),
    handleCode: function(effect) {
        console.log(effect);
        if (effect === 'get_name') {
            return "Arya Stack";
        }
    }
})
console.log(gendry.friendNames);
*/